# Generated by Django 3.2.3 on 2021-09-11 12:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 18, 12, 22, 58, 397292, tzinfo=utc)),
        ),
    ]
